### ISSUE TITLE
[Feat] 프로젝트 글 삭제

### ISSUE THREAD

**Issue by simhani1** [CoDEVumc/CoDEV_BackEnd#61]
## 🛠 Issue

- 프로젝트 글 삭제 기능 추가
## 📝 To-do

- [x] 프로젝트 글 삭제 코드 추가
- [x] 해당 프로젝트 존재 여부 예외처리
- [x] 해당 프로젝트 작성자 여부 예외처리
